### ISSUE TITLE
Is version v0.3.1 compatible with nginx 1.15?

### ISSUE THREAD

**Issue by MuthuChess** [simpl/ngx_devel_kit#31]
Hi,

Please let me know if ngx_devel_kit version v0.3.1 compatible and tested with nginx 1.15? What version of nginx do you recommend?

Also, I am trying to use this in a docker container. What are the libraries needed to install this module? 

Regards,
Muthu.

**Comment by simpl** [comment]
You shouldn't have any issues with Nginx version 1.15, though you probably want to install the latest version of Nginx (1.19).

In terms of other libraries, some elements of the NDK use the zlib, pcre and openssl libraries.  They are usually installed as part of the Nginx installer, since they're also used in some of the core elements of Nginx.  You should refer to the Nginx documentation for compiling Nginx with those libraries, rather than using the system libs.

You may also wish to consider installing OpenResty, which bundles the NDK and a bunch of other useful modules - notably the Nginx Lua Module.  You can find that here: https://openresty.org/en/

**Comment by MuthuChess** [comment]
Thanks for your very quick response. A follow up question.

Since I am trying install this in a docker container, these libraries aren't already available in the image.

Can I install these libraries libpcre3, libpcre3-dev, zlib1g, zlib1g-dev within nginx:1.19 inorder to use NDK or is there any other specific libraries that are recommended for zlib and pcre?

**Comment by simpl** [comment]
zlib, pcre and openssl aren't just for the NDK, they're very common third-party libraries that are used in most Nginx installations.  None of them are required by the NDK, but the functionality of the NDK will be more limited without them (i.e. some functions won't work without some of them).  The NDK will use them if they're available, but they aren't required.

You need to refer to the Nginx documentation on how to compile Nginx with the libraries for Docker.  What you'll need to do is provide commandline arguments to your ```./configure``` call.  You'll need to do a call like:

```
./configure --prefix=PATH --with-zlib=DIR --with-pcre=DIR --with-openssl=DIR ...
```
You can view all the options by calling ```./configure --help```.

You may have to do something special for Docker files, but you'll need to do a search for that.

Specific libraries for zlib / pcre - just download the tarballs from the official websites.  They're usually the first that come up in search engines.

Again, though, this is an Nginx thing, not an NDK thing.
